Handle both ext4 and xfs in convert undercloud step
Change-Id: I88c1dfc7701c3b84fa39dc9df624c7e2bdf0a6c2
Resolves: https://github.com/redhat-openstack/ansible-role-tripleo-image-build/issues/33

diff --git a/templates/undercloud-convert-default.sh.j2 b/templates/undercloud-convert-default.sh.j2
--- a/templates/undercloud-convert-default.sh.j2
+++ b/templates/undercloud-convert-default.sh.j2
@@ -3,7 +3,16 @@
 
 set -eux
 
-xfs_growfs -d /dev/sda1
+FS_TYPE=`findmnt -o FSTYPE -fn /`
+
+if [ "$FS_TYPE" = "xfs" ]; then
+    xfs_growfs -d /dev/sda1
+elif [ "$FS_TYPE" = "ext4" ]; then
+    resize2fs /dev/sda1
+else
+    echo "ERROR: Unknown filesystem, cannot resize."
+    exit 1
+fi
 
 yum remove -y {% for package in artib_undercloud_remove_packages %} {{ package }} {% endfor %}
 
